import * as admin from 'firebase-admin'

admin.initializeApp()

export { confirmSchedule } from './confirmSchedule'
export { submitAvailability } from './submitAvailability'
export { submitWardAssignments } from './submitWardAssignments'
export { adminConfirmSchedule } from './adminConfirmSchedule'
export { adminConfirmWardVisit } from './adminConfirmWardVisit'
export { deleteUser } from './adminActions'
export { manualCalendarSync } from './manualCalendarSync'
export { calendarSync } from './calendarSync'
export { taskCreatedNotification } from './taskCreatedNotification'
export { weeklyReminder } from './weeklyReminder'
export { taskReminder } from './taskReminder'
export { fastSundayBlock } from './fastSundayBlock'
export { getPublicTaskInfo } from './getPublicTaskInfo'
export { submitAvailabilityAnon } from './submitAvailabilityAnon'
export { submitWardAssignmentsAnon } from './submitWardAssignmentsAnon'
export { adminEditSchedule } from './adminEditSchedule'
export { adminDeleteSchedule } from './adminDeleteSchedule'
export { adminCreateSchedule } from './adminCreateSchedule'
export { mergePreRegisteredUser } from './mergePreRegisteredUser'
export { adminAddPreRegisteredUser, adminDeletePreRegisteredUser, adminUpdatePreRegisteredUser } from './adminPreRegistration'
export { getPublicSchedules } from './getPublicSchedules'
export { publicScheduleIcs } from './publicScheduleIcs'
export { registerGeneralAttendance } from './registerGeneralAttendance'
export { publishVisitPlan } from './publishVisitPlan'
export { getSchedulesInRange } from './getSchedulesInRange'
