/**
 * ScheduleSuggestions — shows auto-generated schedule options for an
 * interview/meeting batch and lets admin pick one to confirm.
 *
 * Each option is a conflict-free assignment generated by a different
 * greedy strategy.  Admin reviews and clicks "이 일정으로 확정".
 */
import { useState } from 'react'
import dayjs from 'dayjs'
import 'dayjs/locale/ko'
dayjs.locale('ko')
import clsx from 'clsx'
import { toast } from 'sonner'
import { CheckCircle2, AlertCircle } from 'lucide-react'
import { adminConfirmSchedule } from '@/services/scheduleService'
import { computeInterviewSlots } from '@/services/availabilityService'
import { generateSuggestions, type Respondent, type SuggestionOption } from './schedulingAlgorithm'
import type { Task, RespondedSlot } from '@/types'
import { Button } from '@/components/ui'
import styles from './ScheduleSuggestions.module.scss'

interface ScheduleSuggestionsProps {
  tasks: Task[]
  getPresidentName: (uid: string) => string
  onConfirmed?: () => void
}

export function ScheduleSuggestions({ tasks, getPresidentName, onConfirmed }: ScheduleSuggestionsProps) {
  const [confirmingIdx, setConfirmingIdx] = useState<number | null>(null)

  const respondents: Respondent[] = tasks
    .filter(t => (t.status === 'responded' || t.status === 'completed') && t.respondedSlots?.length)
    .map(t => ({
      uid: t.assignedTo,
      name: getPresidentName(t.assignedTo),
      taskId: t.id,
      availableSlots: (t.respondedSlots as RespondedSlot[]).map(s => ({
        date: s.date,
        startTime: s.startTime,
        endTime: s.endTime,
      })),
    }))

  const suggestions = generateSuggestions(respondents)

  if (respondents.length === 0) {
    return (
      <div className={styles.empty}>
        아직 응답한 회장이 없습니다.
      </div>
    )
  }

  const handleConfirmOption = async (option: SuggestionOption, idx: number) => {
    setConfirmingIdx(idx)
    try {
      const results = await Promise.all(
        option.assignments.map(a =>
          adminConfirmSchedule({ taskId: a.respondent.taskId, slot: a.slot })
        )
      )
      const failed = results.filter(r => !r.success)
      if (failed.length === 0) {
        toast.success(`${option.assignments.length}개 일정이 확정되었습니다!`)
        onConfirmed?.()
      } else {
        toast.error(`${failed.length}건 확정 실패: ${failed[0].error}`)
      }
    } catch (e: unknown) {
      toast.error((e as { message?: string })?.message ?? '확정 중 오류가 발생했습니다.')
    } finally {
      setConfirmingIdx(null)
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <p className={styles.headerTitle}>자동 일정 제안</p>
        <p className={styles.headerDesc}>
          {respondents.length}명의 응답을 바탕으로 중복 없는 일정을 제안합니다.
          검토 후 원하는 안으로 확정하세요.
        </p>
      </div>

      <div className={styles.options}>
        {suggestions.map((option, idx) => (
          <div key={idx} className={clsx(styles.option, option.unassigned.length > 0 && styles.optionIncomplete)}>
            <div className={styles.optionHeader}>
              <span className={styles.optionLabel}>{option.label}</span>
              {option.unassigned.length > 0 ? (
                <span className={styles.optionWarning}>
                  <AlertCircle size={13} /> {option.unassigned.length}명 배정 불가
                </span>
              ) : (
                <span className={styles.optionComplete}>
                  <CheckCircle2 size={13} /> 전원 배정 완료
                </span>
              )}
            </div>

            <div className={styles.optionTable}>
              {option.assignments.map((a, i) => (
                <div key={i} className={styles.assignRow}>
                  <span className={styles.assignName}>{a.respondent.name}</span>
                  <span className={styles.assignSlot}>
                    {dayjs(a.slot.date).format('M/D (ddd)')} {a.slot.startTime}~{a.slot.endTime}
                  </span>
                </div>
              ))}
              {option.unassigned.map(r => (
                <div key={r.uid} className={clsx(styles.assignRow, styles.assignRowMissing)}>
                  <span className={styles.assignName}>{r.name}</span>
                  <span className={styles.assignSlotMissing}>가능한 슬롯 없음</span>
                </div>
              ))}
            </div>

            <Button
              size="sm"
              onClick={() => handleConfirmOption(option, idx)}
              loading={confirmingIdx === idx}
              disabled={confirmingIdx !== null}
              className={styles.confirmBtn}
            >
              이 일정으로 확정
            </Button>
          </div>
        ))}
      </div>

      <p className={styles.notice}>
        * 이미 확정된 일정과의 중복 체크는 되지 않습니다. 개별 슬롯 확정은 위 응답 현황 테이블을 이용하세요.
      </p>
    </div>
  )
}
