/**
 * ScheduleSuggestions — shows auto-generated schedule options for an
 * interview/meeting batch and lets admin pick one to confirm.
 *
 * Each option is a conflict-free assignment generated by a different
 * greedy strategy.  Admin reviews and clicks "이 일정으로 확정".
 */
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import dayjs from 'dayjs'
import 'dayjs/locale/ko'
dayjs.locale('ko')
import clsx from 'clsx'
import { toast } from 'sonner'
import { CheckCircle2, AlertCircle, AlertTriangle } from 'lucide-react'
import { adminConfirmSchedule } from '@/services/scheduleService'
import { computeInterviewSlots } from '@/services/availabilityService'
import { generateSuggestions, type Respondent, type SuggestionOption } from './schedulingAlgorithm'
import type { Task, RespondedSlot } from '@/types'
import type { GeneralSchedule, AppUser } from '@/types'
import { isGeneralScheduleRelevant } from '@/types'
import type { GeneralEventRef } from './schedulingAlgorithm'
import { Button } from '@/components/ui'
import styles from './ScheduleSuggestions.module.scss'

interface ScheduleSuggestionsProps {
  tasks: Task[]
  getPresidentName: (uid: string) => string
  generalSchedules?: GeneralSchedule[]
  currentUser?: AppUser
  onConfirmed?: () => void
}

export function ScheduleSuggestions({ tasks, getPresidentName, generalSchedules, currentUser, onConfirmed }: ScheduleSuggestionsProps) {
  const { t } = useTranslation()
  const [confirmingIdx, setConfirmingIdx] = useState<number | null>(null)

  const respondents: Respondent[] = tasks
    .filter(t => (t.status === 'responded' || t.status === 'completed') && t.respondedSlots?.length)
    .map(t => ({
      uid: t.assignedTo,
      name: getPresidentName(t.assignedTo),
      taskId: t.id,
      availableSlots: (t.respondedSlots as RespondedSlot[]).map(s => ({
        date: s.date,
        startTime: s.startTime,
        endTime: s.endTime,
      })),
    }))

  const relevantGeneralEvents: GeneralEventRef[] = (generalSchedules ?? [])
    .filter(gs => !currentUser || isGeneralScheduleRelevant(gs, currentUser))
    .map(gs => ({ id: gs.id, title: gs.title, date: gs.date }))

  const suggestions = generateSuggestions(respondents, relevantGeneralEvents)

  if (respondents.length === 0) {
    return (
      <div className={styles.empty}>{t('admin.noResponse')}</div>
    )
  }

  const handleConfirmOption = async (option: SuggestionOption, idx: number) => {
    setConfirmingIdx(idx)
    try {
      const results = await Promise.all(
        option.assignments.map(a =>
          adminConfirmSchedule({ taskId: a.respondent.taskId, slot: a.slot })
        )
      )
      const failed = results.filter(r => !r.success)
      if (failed.length === 0) {
        toast.success(t('admin.scheduleConfirmed'))
        onConfirmed?.()
      } else {
        toast.error(`${failed.length}건 확정 실패: ${failed[0].error}`)
      }
    } catch (e: unknown) {
      toast.error((e as { message?: string })?.message ?? t('common.unknownError'))
    } finally {
      setConfirmingIdx(null)
    }
  }

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <p className={styles.headerTitle}>{t('admin.suggestionTitle')}</p>
        <p className={styles.headerDesc}>
          {t('admin.suggestionDesc', { count: respondents.length })}
        </p>
      </div>

      <div className={styles.options}>
        {suggestions.map((option, idx) => (
          <div key={idx} className={clsx(styles.option, option.unassigned.length > 0 && styles.optionIncomplete)}>
            <div className={styles.optionHeader}>
              <span className={styles.optionLabel}>{option.label}</span>
              {option.unassigned.length > 0 ? (
                <span className={styles.optionWarning}>
                  <AlertCircle size={13} /> {option.unassigned.length}{t('ward.unassignedCount', { defaultValue: '명 배정 불가' })}
                </span>
              ) : (
                <span className={styles.optionComplete}>
                  <CheckCircle2 size={13} /> {t('ward.allAssigned', { defaultValue: '전원 배정 완료' })}
                </span>
              )}
            </div>

            <div className={styles.optionTable}>
              {option.assignments.map((a, i) => (
                <div key={i} className={clsx(styles.assignRow, a.conflictingEvent && styles.assignRowConflict)}>
                  <span className={styles.assignName}>{a.respondent.name}</span>
                  <span className={styles.assignSlot}>
                    {dayjs(a.slot.date).format('M/D (ddd)')} {a.slot.startTime}~{a.slot.endTime}
                  </span>
                  {a.conflictingEvent && (
                    <span className={styles.conflictBadge}>
                      <AlertTriangle size={11} />
                      {a.conflictingEvent.title}
                    </span>
                  )}
                </div>
              ))}
              {option.unassigned.map(r => (
                <div key={r.uid} className={clsx(styles.assignRow, styles.assignRowMissing)}>
                  <span className={styles.assignName}>{r.name}</span>
                  <span className={styles.assignSlotMissing}>{t('ward.noSlotAvailable', { defaultValue: '가능한 슬롯 없음' })}</span>
                </div>
              ))}
            </div>

            <Button
              size="sm"
              onClick={() => handleConfirmOption(option, idx)}
              loading={confirmingIdx === idx}
              disabled={confirmingIdx !== null}
              className={styles.confirmBtn}
            >
              {t('admin.confirmOption')}
            </Button>
          </div>
        ))}
      </div>

      <p className={styles.notice}>
        * 이미 확정된 일정과의 중복 체크는 되지 않습니다. 개별 슬롯 확정은 위 응답 현황 테이블을 이용하세요.
      </p>
    </div>
  )
}
